image:
  repository: ghcr.io/flx5/k8s-backup
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

job:
  # Can use https://kueue.sigs.k8s.io/docs/tasks/run/run_cronjobs/ to make sure repositories are updated sequentially
  labels: {}
  schedule: "0 1 * * *"

kopia:
  image:
    repository: kopia/kopia
    tag: "0.22.3"

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

scratch:
  enabled: true

prepareBackupScript: |
  return {}

repository:
  secret: ""

skipCleanup: false
showProgress: false
