image:
  repository: ghcr.io/flx5/k8s-backup
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

kopia:
  image:
    repository: kopia/kopia
    tag: "0.22.3"

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

scratch:
  enabled: true

prepareBackupScript: |
  return {}

repository:
  secret: ""

# TODO Release helm chart with matching image tag